import type { Metadata } from 'next'
// import { ThemeProvider } from "@/components/theme-provider"

import './globals.css';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <ThemeProvider
            attribute="class"
            defaultTheme="system"
            disableTransitionOnChange
          > */}
        <body className='font-primary'>{children}</body>
      {/* </ThemeProvider> */}
    </html>
  )
}
